import { MinStack } from '../../src/easy'

test('0155. Min Stack test case', () => {
  let minStack
  minStack = new MinStack()
  minStack.push(-2)
  minStack.push(0)
  minStack.push(-3)
  expect(minStack.getMin()).toEqual(-3)
  minStack.pop()
  expect(minStack.top()).toEqual(0)
  expect(minStack.getMin()).toEqual(-2)
  minStack = new MinStack()
  minStack.push(0)
  minStack.push(1)
  minStack.push(0)
  expect(minStack.getMin()).toEqual(0)
  minStack.pop()
  expect(minStack.getMin()).toEqual(0)
  minStack.push(2)
  minStack.pop()
  expect(minStack.getMin()).toEqual(0)
  minStack.pop()
  minStack.pop()
  minStack.pop()
})
